import { people } from "./const";

export const tweets = [
  {
    id: 1,
    name: people[0].name,
    username: people[0].username,
    header: "Welcome to Leaflet!",
    tweet: `Leaflet is your go-to web application for identifying different types of leaves quickly and accurately. Whether you're a botanist, a student, a nature enthusiast, or simply curious about the leaves you encounter, our app is designed to help you discover and learn about various leaf species with ease within our FAITH campus!`,
    url: people[0].url,
    image: people[0].image,
    likes: "566",
    comments: "241",
    retweets: "487",
    date: "1:30 PM · May 20, 2024",
  },
  {
    id: 2,
    name: people[1].name,
    username: people[1].username,
    header: "Our Mission",
    tweet: `Is to make plant identification accessible to everyone. By leveraging advanced image recognition technology, Leaflet aims to provide an intuitive and reliable tool for identifying leaves around our FAITH campus. We believe that understanding and appreciating the natural world starts with knowledge, and we are here to help you gain that knowledge one leaf at a time.`,
    url: people[1].url,
    image: people[1].image,
    likes: "241",
    comments: "351",
    retweets: "200",
    date: "1:31 PM · May 20, 2024",
  },
  {
    id: 3,
    name: people[2].name,
    username: people[2].username,
    header: "So how does it work?",
    tweet: `Take a Photo: Snap a clear photo of the leaf you want to identify, or upload an existing image from your device.\nUpload: Upload the image to our web app. \nIdentify: Our powerful AI analyzes the image and provides you with the most likely species, along with detailed information about the leaf.`,
    url: people[2].url,
    image: people[2].image,
    likes: "179",
    comments: "400",
    retweets: "300",
    date: "1:32 PM · May 20, 2024",
  },
  {
    id: 4,
    name: people[3].name,
    username: people[3].username,
    header: "Our Team",
    tweet: `Leaflet is developed by a team of passionate botanists, software engineers, and AI specialists who are dedicated to bridging the gap between technology and nature. We are continuously working to improve our app and expand our database to cover more species and provide even more accurate results.`,
    url: people[3].url,
    image: people[3].image,
    likes: "879",
    comments: "150",
    retweets: "100",
    date: "1:33 PM · May 20, 2024",
  },
  {
    id: 5,
    name: people[4].name,
    username: people[4].username,
    header: "Get in Touch",
    tweet: `We love hearing from our users! Whether you have questions, feedback, or suggestions, feel free to reach out to us at inquiries@leaflet.com. Follow us on social media to stay updated with the latest news and features.`,
    url: people[4].url,
    image: people[4].image,
    likes: "675",
    comments: "200",
    retweets: "150",
    date: "1:34 PM · May 20, 2024",
  },
];
